[package]
name = "mtracker"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive", "cargo"] }
colored = "2.1.0"
dirs = "5.0.1"
regex = "1.10.4"
